language: python

python:
  - "3.6.8"
  - "3.8"

services:
  - docker

before_script:
  - pip install docker-compose
  - echo SECRET_KEY >> cfg
  - echo NEO4J_PWD >> cfg
  - echo n >> cfg
  - ./deploy/deploy_containers < cfg
  - entrypoint="$(echo "$(cat deploy/entrypoint)")"
  - echo "${entrypoint/gunicorn VKInfoSite.wsgi:application -b 0.0.0.0:80/python runtests.py}" > deploy/entrypoint

script:
  - docker-compose run web sh -c "echo Passed all tests!"
