version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: vk-neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=neo4j/neo4j
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: vk-mongo
    ports:
      - "27017:27017"
    networks:
      - backend

  web:
    build:
        context: docker
        dockerfile: Dockerfile
    image: leadness/vk-tracker
    command: python3 /app/VKInfiSite/manage.py runserver 0.0.0.0:8080 --noreload
    container_name: vk-tracker
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge
