version: '3'

services:
  web-app:
    image: vkuserinfo:latest
    ports:
      - "8000:8000"
  mongo:
    image: mongo:latest
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
