name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      - docker

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6.8
        uses: actions/setup-python@v2
          with:
            python-version: 3.6.8
      - name: Install dependencies
        run: |
          pip install docker-compose
      - name: Configure app
        run: |
          echo SECRET_KEY >> cfg
          echo NEO4J_PWD >> cfg
          echo n >> cfg
          ./deploy/deploy_containers < cfg
          entrypoint="$(echo "$(cat deploy/entrypoint)")"
          echo "${entrypoint/manage.py runserver 0.0.0.0:80/runtests.py}" > deploy/entrypoint
      - name: Build docker container & running tests
        run: |
          docker-compose run web sh -c "echo Passed all tests!"
